// const forbiddenErrorHandler(err, req, res, next) => {
//     res.status(404).send
// }

// const internalServerErrorHandler = (err, req, res, next) => {
//   console.error(err.stack);
//   res.status(500).send('알 수 없는 오류가 발생했습니다. 다시 시도해주세요.');
// };

// export { errorHandler };
